// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: nagipath/api/v1/clusters.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterListItem struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Members            int32                  `protobuf:"varint,3,opt,name=members,proto3" json:"members,omitempty"`
	Vendor             string                 `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	GoldenPeerName     string                 `protobuf:"bytes,5,opt,name=golden_peer_name,json=goldenPeerName,proto3" json:"golden_peer_name,omitempty"`
	DriftCount         int32                  `protobuf:"varint,6,opt,name=drift_count,json=driftCount,proto3" json:"drift_count,omitempty"`
	CertsExpiring_30D  int32                  `protobuf:"varint,7,opt,name=certs_expiring_30d,json=certsExpiring30d,proto3" json:"certs_expiring_30d,omitempty"`
	LastCollected      string                 `protobuf:"bytes,8,opt,name=last_collected,json=lastCollected,proto3" json:"last_collected,omitempty"`
	InstancesCollected int32                  `protobuf:"varint,9,opt,name=instances_collected,json=instancesCollected,proto3" json:"instances_collected,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClusterListItem) Reset() {
	*x = ClusterListItem{}
	mi := &file_nagipath_api_v1_clusters_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterListItem) ProtoMessage() {}

func (x *ClusterListItem) ProtoReflect() protoreflect.Message {
	mi := &file_nagipath_api_v1_clusters_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterListItem.ProtoReflect.Descriptor instead.
func (*ClusterListItem) Descriptor() ([]byte, []int) {
	return file_nagipath_api_v1_clusters_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterListItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClusterListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterListItem) GetMembers() int32 {
	if x != nil {
		return x.Members
	}
	return 0
}

func (x *ClusterListItem) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *ClusterListItem) GetGoldenPeerName() string {
	if x != nil {
		return x.GoldenPeerName
	}
	return ""
}

func (x *ClusterListItem) GetDriftCount() int32 {
	if x != nil {
		return x.DriftCount
	}
	return 0
}

func (x *ClusterListItem) GetCertsExpiring_30D() int32 {
	if x != nil {
		return x.CertsExpiring_30D
	}
	return 0
}

func (x *ClusterListItem) GetLastCollected() string {
	if x != nil {
		return x.LastCollected
	}
	return ""
}

func (x *ClusterListItem) GetInstancesCollected() int32 {
	if x != nil {
		return x.InstancesCollected
	}
	return 0
}

type ClusterMemberItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Divergence    *int64                 `protobuf:"varint,3,opt,name=divergence,proto3,oneof" json:"divergence,omitempty"`
	IsGolden      bool                   `protobuf:"varint,4,opt,name=is_golden,json=isGolden,proto3" json:"is_golden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMemberItem) Reset() {
	*x = ClusterMemberItem{}
	mi := &file_nagipath_api_v1_clusters_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMemberItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMemberItem) ProtoMessage() {}

func (x *ClusterMemberItem) ProtoReflect() protoreflect.Message {
	mi := &file_nagipath_api_v1_clusters_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMemberItem.ProtoReflect.Descriptor instead.
func (*ClusterMemberItem) Descriptor() ([]byte, []int) {
	return file_nagipath_api_v1_clusters_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterMemberItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClusterMemberItem) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ClusterMemberItem) GetDivergence() int64 {
	if x != nil && x.Divergence != nil {
		return *x.Divergence
	}
	return 0
}

func (x *ClusterMemberItem) GetIsGolden() bool {
	if x != nil {
		return x.IsGolden
	}
	return false
}

type ClusterDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Members        int32                  `protobuf:"varint,3,opt,name=members,proto3" json:"members,omitempty"`
	Vendor         string                 `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	GoldenPeerName string                 `protobuf:"bytes,5,opt,name=golden_peer_name,json=goldenPeerName,proto3" json:"golden_peer_name,omitempty"`
	LastCollected  string                 `protobuf:"bytes,6,opt,name=last_collected,json=lastCollected,proto3" json:"last_collected,omitempty"`
	MemberList     []*ClusterMemberItem   `protobuf:"bytes,7,rep,name=member_list,json=memberList,proto3" json:"member_list,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClusterDetail) Reset() {
	*x = ClusterDetail{}
	mi := &file_nagipath_api_v1_clusters_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterDetail) ProtoMessage() {}

func (x *ClusterDetail) ProtoReflect() protoreflect.Message {
	mi := &file_nagipath_api_v1_clusters_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterDetail.ProtoReflect.Descriptor instead.
func (*ClusterDetail) Descriptor() ([]byte, []int) {
	return file_nagipath_api_v1_clusters_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClusterDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterDetail) GetMembers() int32 {
	if x != nil {
		return x.Members
	}
	return 0
}

func (x *ClusterDetail) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *ClusterDetail) GetGoldenPeerName() string {
	if x != nil {
		return x.GoldenPeerName
	}
	return ""
}

func (x *ClusterDetail) GetLastCollected() string {
	if x != nil {
		return x.LastCollected
	}
	return ""
}

func (x *ClusterDetail) GetMemberList() []*ClusterMemberItem {
	if x != nil {
		return x.MemberList
	}
	return nil
}

type ClustersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*ClusterListItem     `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	DriftFilter   string                 `protobuf:"bytes,4,opt,name=drift_filter,json=driftFilter,proto3" json:"drift_filter,omitempty"`
	Sort          string                 `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Selected      *ClusterDetail         `protobuf:"bytes,6,opt,name=selected,proto3" json:"selected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClustersResponse) Reset() {
	*x = ClustersResponse{}
	mi := &file_nagipath_api_v1_clusters_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClustersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClustersResponse) ProtoMessage() {}

func (x *ClustersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nagipath_api_v1_clusters_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClustersResponse.ProtoReflect.Descriptor instead.
func (*ClustersResponse) Descriptor() ([]byte, []int) {
	return file_nagipath_api_v1_clusters_proto_rawDescGZIP(), []int{3}
}

func (x *ClustersResponse) GetClusters() []*ClusterListItem {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *ClustersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ClustersResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ClustersResponse) GetDriftFilter() string {
	if x != nil {
		return x.DriftFilter
	}
	return ""
}

func (x *ClustersResponse) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ClustersResponse) GetSelected() *ClusterDetail {
	if x != nil {
		return x.Selected
	}
	return nil
}

var File_nagipath_api_v1_clusters_proto protoreflect.FileDescriptor

const file_nagipath_api_v1_clusters_proto_rawDesc = "" +
	"\n" +
	"\x1enagipath/api/v1/clusters.proto\x12\x0fnagipath.api.v1\"\xb8\x02\n" +
	"\x0fClusterListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\amembers\x18\x03 \x01(\x05R\amembers\x12\x16\n" +
	"\x06vendor\x18\x04 \x01(\tR\x06vendor\x12(\n" +
	"\x10golden_peer_name\x18\x05 \x01(\tR\x0egoldenPeerName\x12\x1f\n" +
	"\vdrift_count\x18\x06 \x01(\x05R\n" +
	"driftCount\x12,\n" +
	"\x12certs_expiring_30d\x18\a \x01(\x05R\x10certsExpiring30d\x12%\n" +
	"\x0elast_collected\x18\b \x01(\tR\rlastCollected\x12/\n" +
	"\x13instances_collected\x18\t \x01(\x05R\x12instancesCollected\"\x97\x01\n" +
	"\x11ClusterMemberItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12#\n" +
	"\n" +
	"divergence\x18\x03 \x01(\x03H\x00R\n" +
	"divergence\x88\x01\x01\x12\x1b\n" +
	"\tis_golden\x18\x04 \x01(\bR\bisGoldenB\r\n" +
	"\v_divergence\"\xfb\x01\n" +
	"\rClusterDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\amembers\x18\x03 \x01(\x05R\amembers\x12\x16\n" +
	"\x06vendor\x18\x04 \x01(\tR\x06vendor\x12(\n" +
	"\x10golden_peer_name\x18\x05 \x01(\tR\x0egoldenPeerName\x12%\n" +
	"\x0elast_collected\x18\x06 \x01(\tR\rlastCollected\x12C\n" +
	"\vmember_list\x18\a \x03(\v2\".nagipath.api.v1.ClusterMemberItemR\n" +
	"memberList\"\xef\x01\n" +
	"\x10ClustersResponse\x12<\n" +
	"\bclusters\x18\x01 \x03(\v2 .nagipath.api.v1.ClusterListItemR\bclusters\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12!\n" +
	"\fdrift_filter\x18\x04 \x01(\tR\vdriftFilter\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\x12:\n" +
	"\bselected\x18\x06 \x01(\v2\x1e.nagipath.api.v1.ClusterDetailR\bselectedB1Z/github.com/nagiflow/nagipath/internal/api/pb;pbb\x06proto3"

var (
	file_nagipath_api_v1_clusters_proto_rawDescOnce sync.Once
	file_nagipath_api_v1_clusters_proto_rawDescData []byte
)

func file_nagipath_api_v1_clusters_proto_rawDescGZIP() []byte {
	file_nagipath_api_v1_clusters_proto_rawDescOnce.Do(func() {
		file_nagipath_api_v1_clusters_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nagipath_api_v1_clusters_proto_rawDesc), len(file_nagipath_api_v1_clusters_proto_rawDesc)))
	})
	return file_nagipath_api_v1_clusters_proto_rawDescData
}

var file_nagipath_api_v1_clusters_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nagipath_api_v1_clusters_proto_goTypes = []any{
	(*ClusterListItem)(nil),   // 0: nagipath.api.v1.ClusterListItem
	(*ClusterMemberItem)(nil), // 1: nagipath.api.v1.ClusterMemberItem
	(*ClusterDetail)(nil),     // 2: nagipath.api.v1.ClusterDetail
	(*ClustersResponse)(nil),  // 3: nagipath.api.v1.ClustersResponse
}
var file_nagipath_api_v1_clusters_proto_depIdxs = []int32{
	1, // 0: nagipath.api.v1.ClusterDetail.member_list:type_name -> nagipath.api.v1.ClusterMemberItem
	0, // 1: nagipath.api.v1.ClustersResponse.clusters:type_name -> nagipath.api.v1.ClusterListItem
	2, // 2: nagipath.api.v1.ClustersResponse.selected:type_name -> nagipath.api.v1.ClusterDetail
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nagipath_api_v1_clusters_proto_init() }
func file_nagipath_api_v1_clusters_proto_init() {
	if File_nagipath_api_v1_clusters_proto != nil {
		return
	}
	file_nagipath_api_v1_clusters_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nagipath_api_v1_clusters_proto_rawDesc), len(file_nagipath_api_v1_clusters_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nagipath_api_v1_clusters_proto_goTypes,
		DependencyIndexes: file_nagipath_api_v1_clusters_proto_depIdxs,
		MessageInfos:      file_nagipath_api_v1_clusters_proto_msgTypes,
	}.Build()
	File_nagipath_api_v1_clusters_proto = out.File
	file_nagipath_api_v1_clusters_proto_goTypes = nil
	file_nagipath_api_v1_clusters_proto_depIdxs = nil
}
