// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nagipath/api/v1/common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ok is every fire-and-forget mutation's response across every service in
// this package (a rename, a decision, a delete) — one shared message instead
// of a near-identical one per RPC, the same reasoning ADR-0018 already gave
// for not generating a type per bare {"ok":true} at all before RPCs existed.
type Ok struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ok) Reset() {
	*x = Ok{}
	mi := &file_nagipath_api_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ok) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ok) ProtoMessage() {}

func (x *Ok) ProtoReflect() protoreflect.Message {
	mi := &file_nagipath_api_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ok.ProtoReflect.Descriptor instead.
func (*Ok) Descriptor() ([]byte, []int) {
	return file_nagipath_api_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Ok) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Empty is every RPC in this package with no request fields — a GET with no
// query parameters. Distinct from google.protobuf.Empty only in staying a
// local type buf doesn't need a well-known-types import for.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_nagipath_api_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_nagipath_api_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_nagipath_api_v1_common_proto_rawDescGZIP(), []int{1}
}

// IdResponse is a create mutation's response across every service in this
// package (a new credential, a new user) — {"ok":true,"id":<n>} typed.
type IdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdResponse) Reset() {
	*x = IdResponse{}
	mi := &file_nagipath_api_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdResponse) ProtoMessage() {}

func (x *IdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nagipath_api_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdResponse.ProtoReflect.Descriptor instead.
func (*IdResponse) Descriptor() ([]byte, []int) {
	return file_nagipath_api_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *IdResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *IdResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_nagipath_api_v1_common_proto protoreflect.FileDescriptor

const file_nagipath_api_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1cnagipath/api/v1/common.proto\x12\x0fnagipath.api.v1\"\x14\n" +
	"\x02Ok\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\a\n" +
	"\x05Empty\",\n" +
	"\n" +
	"IdResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02idB1Z/github.com/nagiflow/nagipath/internal/api/pb;pbb\x06proto3"

var (
	file_nagipath_api_v1_common_proto_rawDescOnce sync.Once
	file_nagipath_api_v1_common_proto_rawDescData []byte
)

func file_nagipath_api_v1_common_proto_rawDescGZIP() []byte {
	file_nagipath_api_v1_common_proto_rawDescOnce.Do(func() {
		file_nagipath_api_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nagipath_api_v1_common_proto_rawDesc), len(file_nagipath_api_v1_common_proto_rawDesc)))
	})
	return file_nagipath_api_v1_common_proto_rawDescData
}

var file_nagipath_api_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nagipath_api_v1_common_proto_goTypes = []any{
	(*Ok)(nil),         // 0: nagipath.api.v1.Ok
	(*Empty)(nil),      // 1: nagipath.api.v1.Empty
	(*IdResponse)(nil), // 2: nagipath.api.v1.IdResponse
}
var file_nagipath_api_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nagipath_api_v1_common_proto_init() }
func file_nagipath_api_v1_common_proto_init() {
	if File_nagipath_api_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nagipath_api_v1_common_proto_rawDesc), len(file_nagipath_api_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nagipath_api_v1_common_proto_goTypes,
		DependencyIndexes: file_nagipath_api_v1_common_proto_depIdxs,
		MessageInfos:      file_nagipath_api_v1_common_proto_msgTypes,
	}.Build()
	File_nagipath_api_v1_common_proto = out.File
	file_nagipath_api_v1_common_proto_goTypes = nil
	file_nagipath_api_v1_common_proto_depIdxs = nil
}
