// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: nagipath/api/v1/nodes.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_ListNodes_FullMethodName            = "/nagipath.api.v1.NodeService/ListNodes"
	NodeService_AddNode_FullMethodName              = "/nagipath.api.v1.NodeService/AddNode"
	NodeService_ImportNodes_FullMethodName          = "/nagipath.api.v1.NodeService/ImportNodes"
	NodeService_GetNodeFile_FullMethodName          = "/nagipath.api.v1.NodeService/GetNodeFile"
	NodeService_WriteNodeFile_FullMethodName        = "/nagipath.api.v1.NodeService/WriteNodeFile"
	NodeService_RestartInstance_FullMethodName      = "/nagipath.api.v1.NodeService/RestartInstance"
	NodeService_GetNode_FullMethodName              = "/nagipath.api.v1.NodeService/GetNode"
	NodeService_CollectNode_FullMethodName          = "/nagipath.api.v1.NodeService/CollectNode"
	NodeService_DeleteNode_FullMethodName           = "/nagipath.api.v1.NodeService/DeleteNode"
	NodeService_ChangeNodeCredential_FullMethodName = "/nagipath.api.v1.NodeService/ChangeNodeCredential"
	NodeService_ChangeNodeBastion_FullMethodName    = "/nagipath.api.v1.NodeService/ChangeNodeBastion"
	NodeService_DecideHostKey_FullMethodName        = "/nagipath.api.v1.NodeService/DecideHostKey"
	NodeService_TestNodeConnection_FullMethodName   = "/nagipath.api.v1.NodeService/TestNodeConnection"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeService: every /nodes and /hostkeys route (internal/api/nodes.go).
// requireAuth wraps the whole gateway; every RPC but ListNodes and GetNode
// calls requireAdminRPC as its own first line — same reasoning as
// DriftService's mutations (drift.proto).
type NodeServiceClient interface {
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*NodesListResponse, error)
	AddNode(ctx context.Context, in *AddNodeRequest, opts ...grpc.CallOption) (*IdResponse, error)
	ImportNodes(ctx context.Context, in *ImportNodesRequest, opts ...grpc.CallOption) (*ImportNodesResponse, error)
	// Declared before GetNode on purpose: grpc-gateway matches patterns in
	// registration order, and GetNode's `/nodes/{id}/{tab}` would otherwise
	// swallow every `/nodes/{node_id}/livefile` as a tab named "livefile".
	GetNodeFile(ctx context.Context, in *GetNodeFileRequest, opts ...grpc.CallOption) (*NodeFileResponse, error)
	WriteNodeFile(ctx context.Context, in *WriteNodeFileRequest, opts ...grpc.CallOption) (*WriteNodeFileResponse, error)
	RestartInstance(ctx context.Context, in *RestartInstanceRequest, opts ...grpc.CallOption) (*RestartInstanceResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*NodeDetailResponse, error)
	CollectNode(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*Ok, error)
	DeleteNode(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*Ok, error)
	ChangeNodeCredential(ctx context.Context, in *ChangeNodeCredentialRequest, opts ...grpc.CallOption) (*Ok, error)
	ChangeNodeBastion(ctx context.Context, in *ChangeNodeBastionRequest, opts ...grpc.CallOption) (*Ok, error)
	DecideHostKey(ctx context.Context, in *DecideHostKeyRequest, opts ...grpc.CallOption) (*DecideHostKeyResponse, error)
	TestNodeConnection(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*NodesListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodesListResponse)
	err := c.cc.Invoke(ctx, NodeService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) AddNode(ctx context.Context, in *AddNodeRequest, opts ...grpc.CallOption) (*IdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdResponse)
	err := c.cc.Invoke(ctx, NodeService_AddNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ImportNodes(ctx context.Context, in *ImportNodesRequest, opts ...grpc.CallOption) (*ImportNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportNodesResponse)
	err := c.cc.Invoke(ctx, NodeService_ImportNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetNodeFile(ctx context.Context, in *GetNodeFileRequest, opts ...grpc.CallOption) (*NodeFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeFileResponse)
	err := c.cc.Invoke(ctx, NodeService_GetNodeFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) WriteNodeFile(ctx context.Context, in *WriteNodeFileRequest, opts ...grpc.CallOption) (*WriteNodeFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteNodeFileResponse)
	err := c.cc.Invoke(ctx, NodeService_WriteNodeFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RestartInstance(ctx context.Context, in *RestartInstanceRequest, opts ...grpc.CallOption) (*RestartInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestartInstanceResponse)
	err := c.cc.Invoke(ctx, NodeService_RestartInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*NodeDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeDetailResponse)
	err := c.cc.Invoke(ctx, NodeService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) CollectNode(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*Ok, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ok)
	err := c.cc.Invoke(ctx, NodeService_CollectNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DeleteNode(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*Ok, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ok)
	err := c.cc.Invoke(ctx, NodeService_DeleteNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ChangeNodeCredential(ctx context.Context, in *ChangeNodeCredentialRequest, opts ...grpc.CallOption) (*Ok, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ok)
	err := c.cc.Invoke(ctx, NodeService_ChangeNodeCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ChangeNodeBastion(ctx context.Context, in *ChangeNodeBastionRequest, opts ...grpc.CallOption) (*Ok, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ok)
	err := c.cc.Invoke(ctx, NodeService_ChangeNodeBastion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DecideHostKey(ctx context.Context, in *DecideHostKeyRequest, opts ...grpc.CallOption) (*DecideHostKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecideHostKeyResponse)
	err := c.cc.Invoke(ctx, NodeService_DecideHostKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) TestNodeConnection(ctx context.Context, in *NodeIdRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestConnectionResponse)
	err := c.cc.Invoke(ctx, NodeService_TestNodeConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
//
// NodeService: every /nodes and /hostkeys route (internal/api/nodes.go).
// requireAuth wraps the whole gateway; every RPC but ListNodes and GetNode
// calls requireAdminRPC as its own first line — same reasoning as
// DriftService's mutations (drift.proto).
type NodeServiceServer interface {
	ListNodes(context.Context, *ListNodesRequest) (*NodesListResponse, error)
	AddNode(context.Context, *AddNodeRequest) (*IdResponse, error)
	ImportNodes(context.Context, *ImportNodesRequest) (*ImportNodesResponse, error)
	// Declared before GetNode on purpose: grpc-gateway matches patterns in
	// registration order, and GetNode's `/nodes/{id}/{tab}` would otherwise
	// swallow every `/nodes/{node_id}/livefile` as a tab named "livefile".
	GetNodeFile(context.Context, *GetNodeFileRequest) (*NodeFileResponse, error)
	WriteNodeFile(context.Context, *WriteNodeFileRequest) (*WriteNodeFileResponse, error)
	RestartInstance(context.Context, *RestartInstanceRequest) (*RestartInstanceResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*NodeDetailResponse, error)
	CollectNode(context.Context, *NodeIdRequest) (*Ok, error)
	DeleteNode(context.Context, *NodeIdRequest) (*Ok, error)
	ChangeNodeCredential(context.Context, *ChangeNodeCredentialRequest) (*Ok, error)
	ChangeNodeBastion(context.Context, *ChangeNodeBastionRequest) (*Ok, error)
	DecideHostKey(context.Context, *DecideHostKeyRequest) (*DecideHostKeyResponse, error)
	TestNodeConnection(context.Context, *NodeIdRequest) (*TestConnectionResponse, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) ListNodes(context.Context, *ListNodesRequest) (*NodesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedNodeServiceServer) AddNode(context.Context, *AddNodeRequest) (*IdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNode not implemented")
}
func (UnimplementedNodeServiceServer) ImportNodes(context.Context, *ImportNodesRequest) (*ImportNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportNodes not implemented")
}
func (UnimplementedNodeServiceServer) GetNodeFile(context.Context, *GetNodeFileRequest) (*NodeFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeFile not implemented")
}
func (UnimplementedNodeServiceServer) WriteNodeFile(context.Context, *WriteNodeFileRequest) (*WriteNodeFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteNodeFile not implemented")
}
func (UnimplementedNodeServiceServer) RestartInstance(context.Context, *RestartInstanceRequest) (*RestartInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartInstance not implemented")
}
func (UnimplementedNodeServiceServer) GetNode(context.Context, *GetNodeRequest) (*NodeDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedNodeServiceServer) CollectNode(context.Context, *NodeIdRequest) (*Ok, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectNode not implemented")
}
func (UnimplementedNodeServiceServer) DeleteNode(context.Context, *NodeIdRequest) (*Ok, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNode not implemented")
}
func (UnimplementedNodeServiceServer) ChangeNodeCredential(context.Context, *ChangeNodeCredentialRequest) (*Ok, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeNodeCredential not implemented")
}
func (UnimplementedNodeServiceServer) ChangeNodeBastion(context.Context, *ChangeNodeBastionRequest) (*Ok, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeNodeBastion not implemented")
}
func (UnimplementedNodeServiceServer) DecideHostKey(context.Context, *DecideHostKeyRequest) (*DecideHostKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecideHostKey not implemented")
}
func (UnimplementedNodeServiceServer) TestNodeConnection(context.Context, *NodeIdRequest) (*TestConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestNodeConnection not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_AddNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).AddNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_AddNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).AddNode(ctx, req.(*AddNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ImportNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ImportNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ImportNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ImportNodes(ctx, req.(*ImportNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetNodeFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetNodeFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetNodeFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetNodeFile(ctx, req.(*GetNodeFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_WriteNodeFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteNodeFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).WriteNodeFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_WriteNodeFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).WriteNodeFile(ctx, req.(*WriteNodeFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RestartInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RestartInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RestartInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RestartInstance(ctx, req.(*RestartInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_CollectNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).CollectNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_CollectNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).CollectNode(ctx, req.(*NodeIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_DeleteNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).DeleteNode(ctx, req.(*NodeIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ChangeNodeCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeNodeCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ChangeNodeCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ChangeNodeCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ChangeNodeCredential(ctx, req.(*ChangeNodeCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ChangeNodeBastion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeNodeBastionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ChangeNodeBastion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ChangeNodeBastion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ChangeNodeBastion(ctx, req.(*ChangeNodeBastionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DecideHostKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecideHostKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).DecideHostKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_DecideHostKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).DecideHostKey(ctx, req.(*DecideHostKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_TestNodeConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).TestNodeConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_TestNodeConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).TestNodeConnection(ctx, req.(*NodeIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nagipath.api.v1.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNodes",
			Handler:    _NodeService_ListNodes_Handler,
		},
		{
			MethodName: "AddNode",
			Handler:    _NodeService_AddNode_Handler,
		},
		{
			MethodName: "ImportNodes",
			Handler:    _NodeService_ImportNodes_Handler,
		},
		{
			MethodName: "GetNodeFile",
			Handler:    _NodeService_GetNodeFile_Handler,
		},
		{
			MethodName: "WriteNodeFile",
			Handler:    _NodeService_WriteNodeFile_Handler,
		},
		{
			MethodName: "RestartInstance",
			Handler:    _NodeService_RestartInstance_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _NodeService_GetNode_Handler,
		},
		{
			MethodName: "CollectNode",
			Handler:    _NodeService_CollectNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _NodeService_DeleteNode_Handler,
		},
		{
			MethodName: "ChangeNodeCredential",
			Handler:    _NodeService_ChangeNodeCredential_Handler,
		},
		{
			MethodName: "ChangeNodeBastion",
			Handler:    _NodeService_ChangeNodeBastion_Handler,
		},
		{
			MethodName: "DecideHostKey",
			Handler:    _NodeService_DecideHostKey_Handler,
		},
		{
			MethodName: "TestNodeConnection",
			Handler:    _NodeService_TestNodeConnection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nagipath/api/v1/nodes.proto",
}
