// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: nagipath/api/v1/rules.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LookupRulePB is one rule in evaluation order, with the scope it came from
// (internal/trace.LookupRule).
type LookupRulePB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ordinal       int32                  `protobuf:"varint,1,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Directive     string                 `protobuf:"bytes,2,opt,name=directive,proto3" json:"directive,omitempty"`
	ActionClass   string                 `protobuf:"bytes,3,opt,name=action_class,json=actionClass,proto3" json:"action_class,omitempty"`
	Args          string                 `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
	Scope         string                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	Inherited     bool                   `protobuf:"varint,6,opt,name=inherited,proto3" json:"inherited,omitempty"`
	Shadowed      bool                   `protobuf:"varint,7,opt,name=shadowed,proto3" json:"shadowed,omitempty"`
	ShadowedBy    string                 `protobuf:"bytes,8,opt,name=shadowed_by,json=shadowedBy,proto3" json:"shadowed_by,omitempty"`
	Path          string                 `protobuf:"bytes,9,opt,name=path,proto3" json:"path,omitempty"`
	ByteStart     int32                  `protobuf:"varint,10,opt,name=byte_start,json=byteStart,proto3" json:"byte_start,omitempty"`
	FileId        int64                  `protobuf:"varint,11,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	SnapshotId    int64                  `protobuf:"varint,12,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRulePB) Reset() {
	*x = LookupRulePB{}
	mi := &file_nagipath_api_v1_rules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRulePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRulePB) ProtoMessage() {}

func (x *LookupRulePB) ProtoReflect() protoreflect.Message {
	mi := &file_nagipath_api_v1_rules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRulePB.ProtoReflect.Descriptor instead.
func (*LookupRulePB) Descriptor() ([]byte, []int) {
	return file_nagipath_api_v1_rules_proto_rawDescGZIP(), []int{0}
}

func (x *LookupRulePB) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *LookupRulePB) GetDirective() string {
	if x != nil {
		return x.Directive
	}
	return ""
}

func (x *LookupRulePB) GetActionClass() string {
	if x != nil {
		return x.ActionClass
	}
	return ""
}

func (x *LookupRulePB) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *LookupRulePB) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *LookupRulePB) GetInherited() bool {
	if x != nil {
		return x.Inherited
	}
	return false
}

func (x *LookupRulePB) GetShadowed() bool {
	if x != nil {
		return x.Shadowed
	}
	return false
}

func (x *LookupRulePB) GetShadowedBy() string {
	if x != nil {
		return x.ShadowedBy
	}
	return ""
}

func (x *LookupRulePB) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LookupRulePB) GetByteStart() int32 {
	if x != nil {
		return x.ByteStart
	}
	return 0
}

func (x *LookupRulePB) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *LookupRulePB) GetSnapshotId() int64 {
	if x != nil {
		return x.SnapshotId
	}
	return 0
}

type LookupBranchPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HopOrdinal    int32                  `protobuf:"varint,1,opt,name=hop_ordinal,json=hopOrdinal,proto3" json:"hop_ordinal,omitempty"`
	Raw           string                 `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupBranchPB) Reset() {
	*x = LookupBranchPB{}
	mi := &file_nagipath_api_v1_rules_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupBranchPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupBranchPB) ProtoMessage() {}

func (x *LookupBranchPB) ProtoReflect() protoreflect.Message {
	mi := &file_nagipath_api_v1_rules_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupBranchPB.ProtoReflect.Descriptor instead.
func (*LookupBranchPB) Descriptor() ([]byte, []int) {
	return file_nagipath_api_v1_rules_proto_rawDescGZIP(), []int{1}
}

func (x *LookupBranchPB) GetHopOrdinal() int32 {
	if x != nil {
		return x.HopOrdinal
	}
	return 0
}

func (x *LookupBranchPB) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *LookupBranchPB) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// LookupResultPB is one Instance's answer (internal/trace.LookupResult) — an
// Instance with no candidates is still a result, so this always carries the
// instance identity even when rules is empty.
type LookupResultPB struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InstId          int64                  `protobuf:"varint,1,opt,name=inst_id,json=instId,proto3" json:"inst_id,omitempty"`
	InstDisplayName string                 `protobuf:"bytes,2,opt,name=inst_display_name,json=instDisplayName,proto3" json:"inst_display_name,omitempty"`
	InstNodeName    string                 `protobuf:"bytes,3,opt,name=inst_node_name,json=instNodeName,proto3" json:"inst_node_name,omitempty"`
	InstVendor      string                 `protobuf:"bytes,4,opt,name=inst_vendor,json=instVendor,proto3" json:"inst_vendor,omitempty"`
	InstDegraded    bool                   `protobuf:"varint,5,opt,name=inst_degraded,json=instDegraded,proto3" json:"inst_degraded,omitempty"`
	ListenerAddress string                 `protobuf:"bytes,6,opt,name=listener_address,json=listenerAddress,proto3" json:"listener_address,omitempty"`
	ListenerPort    int32                  `protobuf:"varint,7,opt,name=listener_port,json=listenerPort,proto3" json:"listener_port,omitempty"`
	ListenerTls     bool                   `protobuf:"varint,8,opt,name=listener_tls,json=listenerTls,proto3" json:"listener_tls,omitempty"`
	SiteName        string                 `protobuf:"bytes,9,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`
	MatchedBy       string                 `protobuf:"bytes,10,opt,name=matched_by,json=matchedBy,proto3" json:"matched_by,omitempty"`
	RoutePattern    string                 `protobuf:"bytes,11,opt,name=route_pattern,json=routePattern,proto3" json:"route_pattern,omitempty"`
	Precedence      string                 `protobuf:"bytes,12,opt,name=precedence,proto3" json:"precedence,omitempty"`
	Degraded        bool                   `protobuf:"varint,13,opt,name=degraded,proto3" json:"degraded,omitempty"`
	Reason          string                 `protobuf:"bytes,14,opt,name=reason,proto3" json:"reason,omitempty"`
	Rules           []*LookupRulePB        `protobuf:"bytes,15,rep,name=rules,proto3" json:"rules,omitempty"`
	Undetermined    []*LookupBranchPB      `protobuf:"bytes,16,rep,name=undetermined,proto3" json:"undetermined,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LookupResultPB) Reset() {
	*x = LookupResultPB{}
	mi := &file_nagipath_api_v1_rules_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResultPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResultPB) ProtoMessage() {}

func (x *LookupResultPB) ProtoReflect() protoreflect.Message {
	mi := &file_nagipath_api_v1_rules_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResultPB.ProtoReflect.Descriptor instead.
func (*LookupResultPB) Descriptor() ([]byte, []int) {
	return file_nagipath_api_v1_rules_proto_rawDescGZIP(), []int{2}
}

func (x *LookupResultPB) GetInstId() int64 {
	if x != nil {
		return x.InstId
	}
	return 0
}

func (x *LookupResultPB) GetInstDisplayName() string {
	if x != nil {
		return x.InstDisplayName
	}
	return ""
}

func (x *LookupResultPB) GetInstNodeName() string {
	if x != nil {
		return x.InstNodeName
	}
	return ""
}

func (x *LookupResultPB) GetInstVendor() string {
	if x != nil {
		return x.InstVendor
	}
	return ""
}

func (x *LookupResultPB) GetInstDegraded() bool {
	if x != nil {
		return x.InstDegraded
	}
	return false
}

func (x *LookupResultPB) GetListenerAddress() string {
	if x != nil {
		return x.ListenerAddress
	}
	return ""
}

func (x *LookupResultPB) GetListenerPort() int32 {
	if x != nil {
		return x.ListenerPort
	}
	return 0
}

func (x *LookupResultPB) GetListenerTls() bool {
	if x != nil {
		return x.ListenerTls
	}
	return false
}

func (x *LookupResultPB) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

func (x *LookupResultPB) GetMatchedBy() string {
	if x != nil {
		return x.MatchedBy
	}
	return ""
}

func (x *LookupResultPB) GetRoutePattern() string {
	if x != nil {
		return x.RoutePattern
	}
	return ""
}

func (x *LookupResultPB) GetPrecedence() string {
	if x != nil {
		return x.Precedence
	}
	return ""
}

func (x *LookupResultPB) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *LookupResultPB) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *LookupResultPB) GetRules() []*LookupRulePB {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *LookupResultPB) GetUndetermined() []*LookupBranchPB {
	if x != nil {
		return x.Undetermined
	}
	return nil
}

type RuleGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Results       []*LookupResultPB      `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleGroup) Reset() {
	*x = RuleGroup{}
	mi := &file_nagipath_api_v1_rules_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleGroup) ProtoMessage() {}

func (x *RuleGroup) ProtoReflect() protoreflect.Message {
	mi := &file_nagipath_api_v1_rules_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleGroup.ProtoReflect.Descriptor instead.
func (*RuleGroup) Descriptor() ([]byte, []int) {
	return file_nagipath_api_v1_rules_proto_rawDescGZIP(), []int{3}
}

func (x *RuleGroup) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *RuleGroup) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *RuleGroup) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RuleGroup) GetResults() []*LookupResultPB {
	if x != nil {
		return x.Results
	}
	return nil
}

type RuleFacet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleFacet) Reset() {
	*x = RuleFacet{}
	mi := &file_nagipath_api_v1_rules_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleFacet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleFacet) ProtoMessage() {}

func (x *RuleFacet) ProtoReflect() protoreflect.Message {
	mi := &file_nagipath_api_v1_rules_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleFacet.ProtoReflect.Descriptor instead.
func (*RuleFacet) Descriptor() ([]byte, []int) {
	return file_nagipath_api_v1_rules_proto_rawDescGZIP(), []int{4}
}

func (x *RuleFacet) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *RuleFacet) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RulesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Scheme          string                 `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Hostname        string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Path            string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Port            int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	ClassesSelected []string               `protobuf:"bytes,5,rep,name=classes_selected,json=classesSelected,proto3" json:"classes_selected,omitempty"`
	VendorsSelected []string               `protobuf:"bytes,6,rep,name=vendors_selected,json=vendorsSelected,proto3" json:"vendors_selected,omitempty"`
	Url             string                 `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	Classes         []string               `protobuf:"bytes,8,rep,name=classes,proto3" json:"classes,omitempty"` // every available action class
	Vendors         []string               `protobuf:"bytes,9,rep,name=vendors,proto3" json:"vendors,omitempty"` // every vendor seen in the fleet
	Asked           bool                   `protobuf:"varint,10,opt,name=asked,proto3" json:"asked,omitempty"`
	Empty           bool                   `protobuf:"varint,11,opt,name=empty,proto3" json:"empty,omitempty"`
	Rules           int32                  `protobuf:"varint,12,opt,name=rules,proto3" json:"rules,omitempty"`
	Nodes           int32                  `protobuf:"varint,13,opt,name=nodes,proto3" json:"nodes,omitempty"`
	Files           int32                  `protobuf:"varint,14,opt,name=files,proto3" json:"files,omitempty"`
	Page            int32                  `protobuf:"varint,15,opt,name=page,proto3" json:"page,omitempty"`
	Pages           int32                  `protobuf:"varint,16,opt,name=pages,proto3" json:"pages,omitempty"`
	From            int32                  `protobuf:"varint,17,opt,name=from,proto3" json:"from,omitempty"`
	To              int32                  `protobuf:"varint,18,opt,name=to,proto3" json:"to,omitempty"`
	VendorFacets    []*RuleFacet           `protobuf:"bytes,19,rep,name=vendor_facets,json=vendorFacets,proto3" json:"vendor_facets,omitempty"`
	ClassFacets     []*RuleFacet           `protobuf:"bytes,20,rep,name=class_facets,json=classFacets,proto3" json:"class_facets,omitempty"`
	RulesUnfiltered int32                  `protobuf:"varint,21,opt,name=rules_unfiltered,json=rulesUnfiltered,proto3" json:"rules_unfiltered,omitempty"`
	Groups          []*RuleGroup           `protobuf:"bytes,22,rep,name=groups,proto3" json:"groups,omitempty"`
	// Silent is every instance that was checked and had no candidate rule —
	// shown collapsed, so it is clear the question was answered, not skipped.
	Silent        []*LookupResultPB `protobuf:"bytes,23,rep,name=silent,proto3" json:"silent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RulesResponse) Reset() {
	*x = RulesResponse{}
	mi := &file_nagipath_api_v1_rules_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RulesResponse) ProtoMessage() {}

func (x *RulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nagipath_api_v1_rules_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RulesResponse.ProtoReflect.Descriptor instead.
func (*RulesResponse) Descriptor() ([]byte, []int) {
	return file_nagipath_api_v1_rules_proto_rawDescGZIP(), []int{5}
}

func (x *RulesResponse) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *RulesResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RulesResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RulesResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RulesResponse) GetClassesSelected() []string {
	if x != nil {
		return x.ClassesSelected
	}
	return nil
}

func (x *RulesResponse) GetVendorsSelected() []string {
	if x != nil {
		return x.VendorsSelected
	}
	return nil
}

func (x *RulesResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RulesResponse) GetClasses() []string {
	if x != nil {
		return x.Classes
	}
	return nil
}

func (x *RulesResponse) GetVendors() []string {
	if x != nil {
		return x.Vendors
	}
	return nil
}

func (x *RulesResponse) GetAsked() bool {
	if x != nil {
		return x.Asked
	}
	return false
}

func (x *RulesResponse) GetEmpty() bool {
	if x != nil {
		return x.Empty
	}
	return false
}

func (x *RulesResponse) GetRules() int32 {
	if x != nil {
		return x.Rules
	}
	return 0
}

func (x *RulesResponse) GetNodes() int32 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

func (x *RulesResponse) GetFiles() int32 {
	if x != nil {
		return x.Files
	}
	return 0
}

func (x *RulesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RulesResponse) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *RulesResponse) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *RulesResponse) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *RulesResponse) GetVendorFacets() []*RuleFacet {
	if x != nil {
		return x.VendorFacets
	}
	return nil
}

func (x *RulesResponse) GetClassFacets() []*RuleFacet {
	if x != nil {
		return x.ClassFacets
	}
	return nil
}

func (x *RulesResponse) GetRulesUnfiltered() int32 {
	if x != nil {
		return x.RulesUnfiltered
	}
	return 0
}

func (x *RulesResponse) GetGroups() []*RuleGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *RulesResponse) GetSilent() []*LookupResultPB {
	if x != nil {
		return x.Silent
	}
	return nil
}

var File_nagipath_api_v1_rules_proto protoreflect.FileDescriptor

const file_nagipath_api_v1_rules_proto_rawDesc = "" +
	"\n" +
	"\x1bnagipath/api/v1/rules.proto\x12\x0fnagipath.api.v1\"\xdb\x02\n" +
	"\fLookupRulePB\x12\x18\n" +
	"\aordinal\x18\x01 \x01(\x05R\aordinal\x12\x1c\n" +
	"\tdirective\x18\x02 \x01(\tR\tdirective\x12!\n" +
	"\faction_class\x18\x03 \x01(\tR\vactionClass\x12\x12\n" +
	"\x04args\x18\x04 \x01(\tR\x04args\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12\x1c\n" +
	"\tinherited\x18\x06 \x01(\bR\tinherited\x12\x1a\n" +
	"\bshadowed\x18\a \x01(\bR\bshadowed\x12\x1f\n" +
	"\vshadowed_by\x18\b \x01(\tR\n" +
	"shadowedBy\x12\x12\n" +
	"\x04path\x18\t \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"byte_start\x18\n" +
	" \x01(\x05R\tbyteStart\x12\x17\n" +
	"\afile_id\x18\v \x01(\x03R\x06fileId\x12\x1f\n" +
	"\vsnapshot_id\x18\f \x01(\x03R\n" +
	"snapshotId\"[\n" +
	"\x0eLookupBranchPB\x12\x1f\n" +
	"\vhop_ordinal\x18\x01 \x01(\x05R\n" +
	"hopOrdinal\x12\x10\n" +
	"\x03raw\x18\x02 \x01(\tR\x03raw\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xe3\x04\n" +
	"\x0eLookupResultPB\x12\x17\n" +
	"\ainst_id\x18\x01 \x01(\x03R\x06instId\x12*\n" +
	"\x11inst_display_name\x18\x02 \x01(\tR\x0finstDisplayName\x12$\n" +
	"\x0einst_node_name\x18\x03 \x01(\tR\finstNodeName\x12\x1f\n" +
	"\vinst_vendor\x18\x04 \x01(\tR\n" +
	"instVendor\x12#\n" +
	"\rinst_degraded\x18\x05 \x01(\bR\finstDegraded\x12)\n" +
	"\x10listener_address\x18\x06 \x01(\tR\x0flistenerAddress\x12#\n" +
	"\rlistener_port\x18\a \x01(\x05R\flistenerPort\x12!\n" +
	"\flistener_tls\x18\b \x01(\bR\vlistenerTls\x12\x1b\n" +
	"\tsite_name\x18\t \x01(\tR\bsiteName\x12\x1d\n" +
	"\n" +
	"matched_by\x18\n" +
	" \x01(\tR\tmatchedBy\x12#\n" +
	"\rroute_pattern\x18\v \x01(\tR\froutePattern\x12\x1e\n" +
	"\n" +
	"precedence\x18\f \x01(\tR\n" +
	"precedence\x12\x1a\n" +
	"\bdegraded\x18\r \x01(\bR\bdegraded\x12\x16\n" +
	"\x06reason\x18\x0e \x01(\tR\x06reason\x123\n" +
	"\x05rules\x18\x0f \x03(\v2\x1d.nagipath.api.v1.LookupRulePBR\x05rules\x12C\n" +
	"\fundetermined\x18\x10 \x03(\v2\x1f.nagipath.api.v1.LookupBranchPBR\fundetermined\"\x8d\x01\n" +
	"\tRuleGroup\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x129\n" +
	"\aresults\x18\x04 \x03(\v2\x1f.nagipath.api.v1.LookupResultPBR\aresults\"7\n" +
	"\tRuleFacet\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xdb\x05\n" +
	"\rRulesResponse\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12)\n" +
	"\x10classes_selected\x18\x05 \x03(\tR\x0fclassesSelected\x12)\n" +
	"\x10vendors_selected\x18\x06 \x03(\tR\x0fvendorsSelected\x12\x10\n" +
	"\x03url\x18\a \x01(\tR\x03url\x12\x18\n" +
	"\aclasses\x18\b \x03(\tR\aclasses\x12\x18\n" +
	"\avendors\x18\t \x03(\tR\avendors\x12\x14\n" +
	"\x05asked\x18\n" +
	" \x01(\bR\x05asked\x12\x14\n" +
	"\x05empty\x18\v \x01(\bR\x05empty\x12\x14\n" +
	"\x05rules\x18\f \x01(\x05R\x05rules\x12\x14\n" +
	"\x05nodes\x18\r \x01(\x05R\x05nodes\x12\x14\n" +
	"\x05files\x18\x0e \x01(\x05R\x05files\x12\x12\n" +
	"\x04page\x18\x0f \x01(\x05R\x04page\x12\x14\n" +
	"\x05pages\x18\x10 \x01(\x05R\x05pages\x12\x12\n" +
	"\x04from\x18\x11 \x01(\x05R\x04from\x12\x0e\n" +
	"\x02to\x18\x12 \x01(\x05R\x02to\x12?\n" +
	"\rvendor_facets\x18\x13 \x03(\v2\x1a.nagipath.api.v1.RuleFacetR\fvendorFacets\x12=\n" +
	"\fclass_facets\x18\x14 \x03(\v2\x1a.nagipath.api.v1.RuleFacetR\vclassFacets\x12)\n" +
	"\x10rules_unfiltered\x18\x15 \x01(\x05R\x0frulesUnfiltered\x122\n" +
	"\x06groups\x18\x16 \x03(\v2\x1a.nagipath.api.v1.RuleGroupR\x06groups\x127\n" +
	"\x06silent\x18\x17 \x03(\v2\x1f.nagipath.api.v1.LookupResultPBR\x06silentB1Z/github.com/nagiflow/nagipath/internal/api/pb;pbb\x06proto3"

var (
	file_nagipath_api_v1_rules_proto_rawDescOnce sync.Once
	file_nagipath_api_v1_rules_proto_rawDescData []byte
)

func file_nagipath_api_v1_rules_proto_rawDescGZIP() []byte {
	file_nagipath_api_v1_rules_proto_rawDescOnce.Do(func() {
		file_nagipath_api_v1_rules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nagipath_api_v1_rules_proto_rawDesc), len(file_nagipath_api_v1_rules_proto_rawDesc)))
	})
	return file_nagipath_api_v1_rules_proto_rawDescData
}

var file_nagipath_api_v1_rules_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_nagipath_api_v1_rules_proto_goTypes = []any{
	(*LookupRulePB)(nil),   // 0: nagipath.api.v1.LookupRulePB
	(*LookupBranchPB)(nil), // 1: nagipath.api.v1.LookupBranchPB
	(*LookupResultPB)(nil), // 2: nagipath.api.v1.LookupResultPB
	(*RuleGroup)(nil),      // 3: nagipath.api.v1.RuleGroup
	(*RuleFacet)(nil),      // 4: nagipath.api.v1.RuleFacet
	(*RulesResponse)(nil),  // 5: nagipath.api.v1.RulesResponse
}
var file_nagipath_api_v1_rules_proto_depIdxs = []int32{
	0, // 0: nagipath.api.v1.LookupResultPB.rules:type_name -> nagipath.api.v1.LookupRulePB
	1, // 1: nagipath.api.v1.LookupResultPB.undetermined:type_name -> nagipath.api.v1.LookupBranchPB
	2, // 2: nagipath.api.v1.RuleGroup.results:type_name -> nagipath.api.v1.LookupResultPB
	4, // 3: nagipath.api.v1.RulesResponse.vendor_facets:type_name -> nagipath.api.v1.RuleFacet
	4, // 4: nagipath.api.v1.RulesResponse.class_facets:type_name -> nagipath.api.v1.RuleFacet
	3, // 5: nagipath.api.v1.RulesResponse.groups:type_name -> nagipath.api.v1.RuleGroup
	2, // 6: nagipath.api.v1.RulesResponse.silent:type_name -> nagipath.api.v1.LookupResultPB
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_nagipath_api_v1_rules_proto_init() }
func file_nagipath_api_v1_rules_proto_init() {
	if File_nagipath_api_v1_rules_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nagipath_api_v1_rules_proto_rawDesc), len(file_nagipath_api_v1_rules_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nagipath_api_v1_rules_proto_goTypes,
		DependencyIndexes: file_nagipath_api_v1_rules_proto_depIdxs,
		MessageInfos:      file_nagipath_api_v1_rules_proto_msgTypes,
	}.Build()
	File_nagipath_api_v1_rules_proto = out.File
	file_nagipath_api_v1_rules_proto_goTypes = nil
	file_nagipath_api_v1_rules_proto_depIdxs = nil
}
