// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: nagipath/api/v1/search.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuleHitPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        int64                  `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	InstanceId    int64                  `protobuf:"varint,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	SnapshotId    int64                  `protobuf:"varint,3,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	FileId        int64                  `protobuf:"varint,4,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Instance      string                 `protobuf:"bytes,5,opt,name=instance,proto3" json:"instance,omitempty"`
	Vendor        string                 `protobuf:"bytes,6,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Node          string                 `protobuf:"bytes,7,opt,name=node,proto3" json:"node,omitempty"`
	Cluster       string                 `protobuf:"bytes,8,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Directive     string                 `protobuf:"bytes,9,opt,name=directive,proto3" json:"directive,omitempty"`
	ActionClass   string                 `protobuf:"bytes,10,opt,name=action_class,json=actionClass,proto3" json:"action_class,omitempty"`
	Args          string                 `protobuf:"bytes,11,opt,name=args,proto3" json:"args,omitempty"`
	Raw           string                 `protobuf:"bytes,12,opt,name=raw,proto3" json:"raw,omitempty"`
	Path          string                 `protobuf:"bytes,13,opt,name=path,proto3" json:"path,omitempty"`
	ByteStart     int32                  `protobuf:"varint,14,opt,name=byte_start,json=byteStart,proto3" json:"byte_start,omitempty"`
	Shadowed      bool                   `protobuf:"varint,15,opt,name=shadowed,proto3" json:"shadowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleHitPB) Reset() {
	*x = RuleHitPB{}
	mi := &file_nagipath_api_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleHitPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleHitPB) ProtoMessage() {}

func (x *RuleHitPB) ProtoReflect() protoreflect.Message {
	mi := &file_nagipath_api_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleHitPB.ProtoReflect.Descriptor instead.
func (*RuleHitPB) Descriptor() ([]byte, []int) {
	return file_nagipath_api_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *RuleHitPB) GetRuleId() int64 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *RuleHitPB) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *RuleHitPB) GetSnapshotId() int64 {
	if x != nil {
		return x.SnapshotId
	}
	return 0
}

func (x *RuleHitPB) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *RuleHitPB) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *RuleHitPB) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *RuleHitPB) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *RuleHitPB) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *RuleHitPB) GetDirective() string {
	if x != nil {
		return x.Directive
	}
	return ""
}

func (x *RuleHitPB) GetActionClass() string {
	if x != nil {
		return x.ActionClass
	}
	return ""
}

func (x *RuleHitPB) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *RuleHitPB) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *RuleHitPB) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RuleHitPB) GetByteStart() int32 {
	if x != nil {
		return x.ByteStart
	}
	return 0
}

func (x *RuleHitPB) GetShadowed() bool {
	if x != nil {
		return x.Shadowed
	}
	return false
}

type TextHitPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        int64                  `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	SnapshotId    int64                  `protobuf:"varint,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	InstanceId    int64                  `protobuf:"varint,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Instance      string                 `protobuf:"bytes,4,opt,name=instance,proto3" json:"instance,omitempty"`
	Vendor        string                 `protobuf:"bytes,5,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Node          string                 `protobuf:"bytes,6,opt,name=node,proto3" json:"node,omitempty"`
	Cluster       string                 `protobuf:"bytes,7,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Path          string                 `protobuf:"bytes,8,opt,name=path,proto3" json:"path,omitempty"`
	Snippet       string                 `protobuf:"bytes,9,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextHitPB) Reset() {
	*x = TextHitPB{}
	mi := &file_nagipath_api_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextHitPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextHitPB) ProtoMessage() {}

func (x *TextHitPB) ProtoReflect() protoreflect.Message {
	mi := &file_nagipath_api_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextHitPB.ProtoReflect.Descriptor instead.
func (*TextHitPB) Descriptor() ([]byte, []int) {
	return file_nagipath_api_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *TextHitPB) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *TextHitPB) GetSnapshotId() int64 {
	if x != nil {
		return x.SnapshotId
	}
	return 0
}

func (x *TextHitPB) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *TextHitPB) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *TextHitPB) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *TextHitPB) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *TextHitPB) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *TextHitPB) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TextHitPB) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

type SearchGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    int64                  `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	Node          string                 `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	Vendor        string                 `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	SnapshotId    int64                  `protobuf:"varint,5,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	FileId        int64                  `protobuf:"varint,6,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	Rules         []*RuleHitPB           `protobuf:"bytes,8,rep,name=rules,proto3" json:"rules,omitempty"`
	Texts         []*TextHitPB           `protobuf:"bytes,9,rep,name=texts,proto3" json:"texts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGroup) Reset() {
	*x = SearchGroup{}
	mi := &file_nagipath_api_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGroup) ProtoMessage() {}

func (x *SearchGroup) ProtoReflect() protoreflect.Message {
	mi := &file_nagipath_api_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGroup.ProtoReflect.Descriptor instead.
func (*SearchGroup) Descriptor() ([]byte, []int) {
	return file_nagipath_api_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchGroup) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *SearchGroup) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *SearchGroup) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *SearchGroup) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *SearchGroup) GetSnapshotId() int64 {
	if x != nil {
		return x.SnapshotId
	}
	return 0
}

func (x *SearchGroup) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *SearchGroup) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SearchGroup) GetRules() []*RuleHitPB {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *SearchGroup) GetTexts() []*TextHitPB {
	if x != nil {
		return x.Texts
	}
	return nil
}

type SearchFacet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFacet) Reset() {
	*x = SearchFacet{}
	mi := &file_nagipath_api_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFacet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFacet) ProtoMessage() {}

func (x *SearchFacet) ProtoReflect() protoreflect.Message {
	mi := &file_nagipath_api_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFacet.ProtoReflect.Descriptor instead.
func (*SearchFacet) Descriptor() ([]byte, []int) {
	return file_nagipath_api_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchFacet) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SearchFacet) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	MatchMode     string                 `protobuf:"bytes,2,opt,name=match_mode,json=matchMode,proto3" json:"match_mode,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Vendors       []*SearchFacet         `protobuf:"bytes,4,rep,name=vendors,proto3" json:"vendors,omitempty"`
	Files         []*SearchFacet         `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`
	Clusters      []*SearchFacet         `protobuf:"bytes,6,rep,name=clusters,proto3" json:"clusters,omitempty"`
	SnapshotAge   []*SearchFacet         `protobuf:"bytes,7,rep,name=snapshot_age,json=snapshotAge,proto3" json:"snapshot_age,omitempty"`
	SelVendor     []string               `protobuf:"bytes,8,rep,name=sel_vendor,json=selVendor,proto3" json:"sel_vendor,omitempty"`
	SelFile       []string               `protobuf:"bytes,9,rep,name=sel_file,json=selFile,proto3" json:"sel_file,omitempty"`
	SelCluster    []string               `protobuf:"bytes,10,rep,name=sel_cluster,json=selCluster,proto3" json:"sel_cluster,omitempty"`
	SelAge        []string               `protobuf:"bytes,11,rep,name=sel_age,json=selAge,proto3" json:"sel_age,omitempty"`
	Matches       int32                  `protobuf:"varint,12,opt,name=matches,proto3" json:"matches,omitempty"`
	FilesHit      int32                  `protobuf:"varint,13,opt,name=files_hit,json=filesHit,proto3" json:"files_hit,omitempty"`
	NodesHit      int32                  `protobuf:"varint,14,opt,name=nodes_hit,json=nodesHit,proto3" json:"nodes_hit,omitempty"`
	Instances     int32                  `protobuf:"varint,15,opt,name=instances,proto3" json:"instances,omitempty"`
	From          int32                  `protobuf:"varint,16,opt,name=from,proto3" json:"from,omitempty"`
	To            int32                  `protobuf:"varint,17,opt,name=to,proto3" json:"to,omitempty"`
	Page          int32                  `protobuf:"varint,18,opt,name=page,proto3" json:"page,omitempty"`
	Pages         int32                  `protobuf:"varint,19,opt,name=pages,proto3" json:"pages,omitempty"`
	Duration      string                 `protobuf:"bytes,20,opt,name=duration,proto3" json:"duration,omitempty"`
	Error         string                 `protobuf:"bytes,21,opt,name=error,proto3" json:"error,omitempty"`
	RegexError    string                 `protobuf:"bytes,22,opt,name=regex_error,json=regexError,proto3" json:"regex_error,omitempty"`
	Groups        []*SearchGroup         `protobuf:"bytes,23,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_nagipath_api_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nagipath_api_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_nagipath_api_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchResponse) GetMatchMode() string {
	if x != nil {
		return x.MatchMode
	}
	return ""
}

func (x *SearchResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *SearchResponse) GetVendors() []*SearchFacet {
	if x != nil {
		return x.Vendors
	}
	return nil
}

func (x *SearchResponse) GetFiles() []*SearchFacet {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *SearchResponse) GetClusters() []*SearchFacet {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *SearchResponse) GetSnapshotAge() []*SearchFacet {
	if x != nil {
		return x.SnapshotAge
	}
	return nil
}

func (x *SearchResponse) GetSelVendor() []string {
	if x != nil {
		return x.SelVendor
	}
	return nil
}

func (x *SearchResponse) GetSelFile() []string {
	if x != nil {
		return x.SelFile
	}
	return nil
}

func (x *SearchResponse) GetSelCluster() []string {
	if x != nil {
		return x.SelCluster
	}
	return nil
}

func (x *SearchResponse) GetSelAge() []string {
	if x != nil {
		return x.SelAge
	}
	return nil
}

func (x *SearchResponse) GetMatches() int32 {
	if x != nil {
		return x.Matches
	}
	return 0
}

func (x *SearchResponse) GetFilesHit() int32 {
	if x != nil {
		return x.FilesHit
	}
	return 0
}

func (x *SearchResponse) GetNodesHit() int32 {
	if x != nil {
		return x.NodesHit
	}
	return 0
}

func (x *SearchResponse) GetInstances() int32 {
	if x != nil {
		return x.Instances
	}
	return 0
}

func (x *SearchResponse) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *SearchResponse) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *SearchResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchResponse) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *SearchResponse) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *SearchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SearchResponse) GetRegexError() string {
	if x != nil {
		return x.RegexError
	}
	return ""
}

func (x *SearchResponse) GetGroups() []*SearchGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GetSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	Match         string                 `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Vendor        []string               `protobuf:"bytes,4,rep,name=vendor,proto3" json:"vendor,omitempty"`
	File          []string               `protobuf:"bytes,5,rep,name=file,proto3" json:"file,omitempty"`
	Cluster       []string               `protobuf:"bytes,6,rep,name=cluster,proto3" json:"cluster,omitempty"`
	Age           []string               `protobuf:"bytes,7,rep,name=age,proto3" json:"age,omitempty"`
	Page          int32                  `protobuf:"varint,8,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSearchRequest) Reset() {
	*x = GetSearchRequest{}
	mi := &file_nagipath_api_v1_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchRequest) ProtoMessage() {}

func (x *GetSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nagipath_api_v1_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchRequest.ProtoReflect.Descriptor instead.
func (*GetSearchRequest) Descriptor() ([]byte, []int) {
	return file_nagipath_api_v1_search_proto_rawDescGZIP(), []int{5}
}

func (x *GetSearchRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *GetSearchRequest) GetMatch() string {
	if x != nil {
		return x.Match
	}
	return ""
}

func (x *GetSearchRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GetSearchRequest) GetVendor() []string {
	if x != nil {
		return x.Vendor
	}
	return nil
}

func (x *GetSearchRequest) GetFile() []string {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *GetSearchRequest) GetCluster() []string {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *GetSearchRequest) GetAge() []string {
	if x != nil {
		return x.Age
	}
	return nil
}

func (x *GetSearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

var File_nagipath_api_v1_search_proto protoreflect.FileDescriptor

const file_nagipath_api_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x1cnagipath/api/v1/search.proto\x12\x0fnagipath.api.v1\x1a\x1cgoogle/api/annotations.proto\"\x97\x03\n" +
	"\tRuleHitPB\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\x03R\x06ruleId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\x03R\n" +
	"instanceId\x12\x1f\n" +
	"\vsnapshot_id\x18\x03 \x01(\x03R\n" +
	"snapshotId\x12\x17\n" +
	"\afile_id\x18\x04 \x01(\x03R\x06fileId\x12\x1a\n" +
	"\binstance\x18\x05 \x01(\tR\binstance\x12\x16\n" +
	"\x06vendor\x18\x06 \x01(\tR\x06vendor\x12\x12\n" +
	"\x04node\x18\a \x01(\tR\x04node\x12\x18\n" +
	"\acluster\x18\b \x01(\tR\acluster\x12\x1c\n" +
	"\tdirective\x18\t \x01(\tR\tdirective\x12!\n" +
	"\faction_class\x18\n" +
	" \x01(\tR\vactionClass\x12\x12\n" +
	"\x04args\x18\v \x01(\tR\x04args\x12\x10\n" +
	"\x03raw\x18\f \x01(\tR\x03raw\x12\x12\n" +
	"\x04path\x18\r \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"byte_start\x18\x0e \x01(\x05R\tbyteStart\x12\x1a\n" +
	"\bshadowed\x18\x0f \x01(\bR\bshadowed\"\xf6\x01\n" +
	"\tTextHitPB\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\x03R\x06fileId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\x03R\n" +
	"snapshotId\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\x03R\n" +
	"instanceId\x12\x1a\n" +
	"\binstance\x18\x04 \x01(\tR\binstance\x12\x16\n" +
	"\x06vendor\x18\x05 \x01(\tR\x06vendor\x12\x12\n" +
	"\x04node\x18\x06 \x01(\tR\x04node\x12\x18\n" +
	"\acluster\x18\a \x01(\tR\acluster\x12\x12\n" +
	"\x04path\x18\b \x01(\tR\x04path\x12\x18\n" +
	"\asnippet\x18\t \x01(\tR\asnippet\"\xa8\x02\n" +
	"\vSearchGroup\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x03R\n" +
	"instanceId\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x12\n" +
	"\x04node\x18\x03 \x01(\tR\x04node\x12\x16\n" +
	"\x06vendor\x18\x04 \x01(\tR\x06vendor\x12\x1f\n" +
	"\vsnapshot_id\x18\x05 \x01(\x03R\n" +
	"snapshotId\x12\x17\n" +
	"\afile_id\x18\x06 \x01(\x03R\x06fileId\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x120\n" +
	"\x05rules\x18\b \x03(\v2\x1a.nagipath.api.v1.RuleHitPBR\x05rules\x120\n" +
	"\x05texts\x18\t \x03(\v2\x1a.nagipath.api.v1.TextHitPBR\x05texts\"9\n" +
	"\vSearchFacet\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xff\x05\n" +
	"\x0eSearchResponse\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"match_mode\x18\x02 \x01(\tR\tmatchMode\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x126\n" +
	"\avendors\x18\x04 \x03(\v2\x1c.nagipath.api.v1.SearchFacetR\avendors\x122\n" +
	"\x05files\x18\x05 \x03(\v2\x1c.nagipath.api.v1.SearchFacetR\x05files\x128\n" +
	"\bclusters\x18\x06 \x03(\v2\x1c.nagipath.api.v1.SearchFacetR\bclusters\x12?\n" +
	"\fsnapshot_age\x18\a \x03(\v2\x1c.nagipath.api.v1.SearchFacetR\vsnapshotAge\x12\x1d\n" +
	"\n" +
	"sel_vendor\x18\b \x03(\tR\tselVendor\x12\x19\n" +
	"\bsel_file\x18\t \x03(\tR\aselFile\x12\x1f\n" +
	"\vsel_cluster\x18\n" +
	" \x03(\tR\n" +
	"selCluster\x12\x17\n" +
	"\asel_age\x18\v \x03(\tR\x06selAge\x12\x18\n" +
	"\amatches\x18\f \x01(\x05R\amatches\x12\x1b\n" +
	"\tfiles_hit\x18\r \x01(\x05R\bfilesHit\x12\x1b\n" +
	"\tnodes_hit\x18\x0e \x01(\x05R\bnodesHit\x12\x1c\n" +
	"\tinstances\x18\x0f \x01(\x05R\tinstances\x12\x12\n" +
	"\x04from\x18\x10 \x01(\x05R\x04from\x12\x0e\n" +
	"\x02to\x18\x11 \x01(\x05R\x02to\x12\x12\n" +
	"\x04page\x18\x12 \x01(\x05R\x04page\x12\x14\n" +
	"\x05pages\x18\x13 \x01(\x05R\x05pages\x12\x1a\n" +
	"\bduration\x18\x14 \x01(\tR\bduration\x12\x14\n" +
	"\x05error\x18\x15 \x01(\tR\x05error\x12\x1f\n" +
	"\vregex_error\x18\x16 \x01(\tR\n" +
	"regexError\x124\n" +
	"\x06groups\x18\x17 \x03(\v2\x1c.nagipath.api.v1.SearchGroupR\x06groups\"\xb8\x01\n" +
	"\x10GetSearchRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12\x14\n" +
	"\x05match\x18\x02 \x01(\tR\x05match\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x16\n" +
	"\x06vendor\x18\x04 \x03(\tR\x06vendor\x12\x12\n" +
	"\x04file\x18\x05 \x03(\tR\x04file\x12\x18\n" +
	"\acluster\x18\x06 \x03(\tR\acluster\x12\x10\n" +
	"\x03age\x18\a \x03(\tR\x03age\x12\x12\n" +
	"\x04page\x18\b \x01(\x05R\x04page2q\n" +
	"\rSearchService\x12`\n" +
	"\tGetSearch\x12!.nagipath.api.v1.GetSearchRequest\x1a\x1f.nagipath.api.v1.SearchResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/searchB1Z/github.com/nagiflow/nagipath/internal/api/pb;pbb\x06proto3"

var (
	file_nagipath_api_v1_search_proto_rawDescOnce sync.Once
	file_nagipath_api_v1_search_proto_rawDescData []byte
)

func file_nagipath_api_v1_search_proto_rawDescGZIP() []byte {
	file_nagipath_api_v1_search_proto_rawDescOnce.Do(func() {
		file_nagipath_api_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nagipath_api_v1_search_proto_rawDesc), len(file_nagipath_api_v1_search_proto_rawDesc)))
	})
	return file_nagipath_api_v1_search_proto_rawDescData
}

var file_nagipath_api_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_nagipath_api_v1_search_proto_goTypes = []any{
	(*RuleHitPB)(nil),        // 0: nagipath.api.v1.RuleHitPB
	(*TextHitPB)(nil),        // 1: nagipath.api.v1.TextHitPB
	(*SearchGroup)(nil),      // 2: nagipath.api.v1.SearchGroup
	(*SearchFacet)(nil),      // 3: nagipath.api.v1.SearchFacet
	(*SearchResponse)(nil),   // 4: nagipath.api.v1.SearchResponse
	(*GetSearchRequest)(nil), // 5: nagipath.api.v1.GetSearchRequest
}
var file_nagipath_api_v1_search_proto_depIdxs = []int32{
	0, // 0: nagipath.api.v1.SearchGroup.rules:type_name -> nagipath.api.v1.RuleHitPB
	1, // 1: nagipath.api.v1.SearchGroup.texts:type_name -> nagipath.api.v1.TextHitPB
	3, // 2: nagipath.api.v1.SearchResponse.vendors:type_name -> nagipath.api.v1.SearchFacet
	3, // 3: nagipath.api.v1.SearchResponse.files:type_name -> nagipath.api.v1.SearchFacet
	3, // 4: nagipath.api.v1.SearchResponse.clusters:type_name -> nagipath.api.v1.SearchFacet
	3, // 5: nagipath.api.v1.SearchResponse.snapshot_age:type_name -> nagipath.api.v1.SearchFacet
	2, // 6: nagipath.api.v1.SearchResponse.groups:type_name -> nagipath.api.v1.SearchGroup
	5, // 7: nagipath.api.v1.SearchService.GetSearch:input_type -> nagipath.api.v1.GetSearchRequest
	4, // 8: nagipath.api.v1.SearchService.GetSearch:output_type -> nagipath.api.v1.SearchResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_nagipath_api_v1_search_proto_init() }
func file_nagipath_api_v1_search_proto_init() {
	if File_nagipath_api_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nagipath_api_v1_search_proto_rawDesc), len(file_nagipath_api_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nagipath_api_v1_search_proto_goTypes,
		DependencyIndexes: file_nagipath_api_v1_search_proto_depIdxs,
		MessageInfos:      file_nagipath_api_v1_search_proto_msgTypes,
	}.Build()
	File_nagipath_api_v1_search_proto = out.File
	file_nagipath_api_v1_search_proto_goTypes = nil
	file_nagipath_api_v1_search_proto_depIdxs = nil
}
