// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file nagipath/api/v1/certificates.proto (package nagipath.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { DriftClusterOption } from "./drift_pb";
import { file_nagipath_api_v1_drift } from "./drift_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file nagipath/api/v1/certificates.proto.
 */
export const file_nagipath_api_v1_certificates: GenFile = /*@__PURE__*/
  fileDesc("CiJuYWdpcGF0aC9hcGkvdjEvY2VydGlmaWNhdGVzLnByb3RvEg9uYWdpcGF0aC5hcGkudjEixAEKE0NlcnRpZmljYXRlTGlzdEl0ZW0SCgoCaWQYASABKAMSEwoLZmluZ2VycHJpbnQYAiABKAkSEgoKc3ViamVjdF9jbhgDIAEoCRIRCglpc3N1ZXJfZG4YBCABKAkSEgoKbm90X2JlZm9yZRgFIAEoCRIRCglub3RfYWZ0ZXIYBiABKAkSDQoFaXNfY2EYByABKAgSEAoIYmluZGluZ3MYCCABKAUSDQoFaG9zdHMYCSABKAkSDgoGc2VydmVzGAogAygJIu4BChhDZXJ0aWZpY2F0ZXNMaXN0UmVzcG9uc2USMgoEbGlzdBgBIAMoCzIkLm5hZ2lwYXRoLmFwaS52MS5DZXJ0aWZpY2F0ZUxpc3RJdGVtEg8KB2V4cGlyZXMYAiABKAkSDgoGaXNzdWVyGAMgASgJEg8KB2NsdXN0ZXIYBCABKAkSEwoLaW5jbHVkZV9jYXMYBSABKAgSDwoHaXNzdWVycxgGIAMoCRI1CghjbHVzdGVycxgHIAMoCzIjLm5hZ2lwYXRoLmFwaS52MS5EcmlmdENsdXN0ZXJPcHRpb24SDwoHc3VtbWFyeRgIIAEoCSKSAgoLQ2VydGlmaWNhdGUSCgoCaWQYASABKAMSEwoLZmluZ2VycHJpbnQYAiABKAkSEgoKc3ViamVjdF9jbhgDIAEoCRISCgpzdWJqZWN0X2RuGAQgASgJEgwKBHNhbnMYBSADKAkSEQoJaXNzdWVyX2RuGAYgASgJEg4KBnNlcmlhbBgHIAEoCRISCgpub3RfYmVmb3JlGAggASgJEhEKCW5vdF9hZnRlchgJIAEoCRIVCg1rZXlfYWxnb3JpdGhtGAogASgJEhAKCGtleV9iaXRzGAsgASgFEhUKDXNpZ19hbGdvcml0aG0YDCABKAkSEwoLc2VsZl9zaWduZWQYDSABKAgSDQoFaXNfY2EYDiABKAgiyQEKC0NlcnRCaW5kaW5nEhMKC2luc3RhbmNlX2lkGAEgASgDEhAKCGluc3RhbmNlGAIgASgJEgwKBG5vZGUYAyABKAkSFAoMY2x1c3Rlcl9uYW1lGAQgASgJEhMKC3NuYXBzaG90X2lkGAUgASgDEg8KB2ZpbGVfaWQYBiABKAMSEQoJZmlsZV9wYXRoGAcgASgJEhIKCnNpdGVfbmFtZXMYCCABKAkSDAoEcG9ydBgJIAEoBRIUCgxjb21iaW5lZF9wZW0YCiABKAgiRQoMQ2VydEZpbGVQYXRoEgwKBHBhdGgYASABKAkSEgoKbm9kZV9jb3VudBgCIAEoBRITCgtidW5kbGVfdHlwZRgDIAEoCSLpAQoZQ2VydGlmaWNhdGVEZXRhaWxSZXNwb25zZRIqCgRjZXJ0GAEgASgLMhwubmFnaXBhdGguYXBpLnYxLkNlcnRpZmljYXRlEi4KCGJpbmRpbmdzGAIgAygLMhwubmFnaXBhdGguYXBpLnYxLkNlcnRCaW5kaW5nEjEKCmZpbGVfcGF0aHMYAyADKAsyHS5uYWdpcGF0aC5hcGkudjEuQ2VydEZpbGVQYXRoEhIKCmFjdGl2ZV90YWIYBCABKAkSFQoNYmluZGluZ19jb3VudBgFIAEoBRISCgpmaWxlX2NvdW50GAYgASgFQjFaL2dpdGh1Yi5jb20vbmFnaWZsb3cvbmFnaXBhdGgvaW50ZXJuYWwvYXBpL3BiO3BiYgZwcm90bzM", [file_nagipath_api_v1_drift]);

/**
 * @generated from message nagipath.api.v1.CertificateListItem
 */
export type CertificateListItem = Message<"nagipath.api.v1.CertificateListItem"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string fingerprint = 2;
   */
  fingerprint: string;

  /**
   * @generated from field: string subject_cn = 3;
   */
  subjectCn: string;

  /**
   * @generated from field: string issuer_dn = 4;
   */
  issuerDn: string;

  /**
   * @generated from field: string not_before = 5;
   */
  notBefore: string;

  /**
   * @generated from field: string not_after = 6;
   */
  notAfter: string;

  /**
   * @generated from field: bool is_ca = 7;
   */
  isCa: boolean;

  /**
   * @generated from field: int32 bindings = 8;
   */
  bindings: number;

  /**
   * @generated from field: string hosts = 9;
   */
  hosts: string;

  /**
   * @generated from field: repeated string serves = 10;
   */
  serves: string[];
};

/**
 * Describes the message nagipath.api.v1.CertificateListItem.
 * Use `create(CertificateListItemSchema)` to create a new message.
 */
export const CertificateListItemSchema: GenMessage<CertificateListItem> = /*@__PURE__*/
  messageDesc(file_nagipath_api_v1_certificates, 0);

/**
 * @generated from message nagipath.api.v1.CertificatesListResponse
 */
export type CertificatesListResponse = Message<"nagipath.api.v1.CertificatesListResponse"> & {
  /**
   * @generated from field: repeated nagipath.api.v1.CertificateListItem list = 1;
   */
  list: CertificateListItem[];

  /**
   * @generated from field: string expires = 2;
   */
  expires: string;

  /**
   * @generated from field: string issuer = 3;
   */
  issuer: string;

  /**
   * @generated from field: string cluster = 4;
   */
  cluster: string;

  /**
   * @generated from field: bool include_cas = 5;
   */
  includeCas: boolean;

  /**
   * @generated from field: repeated string issuers = 6;
   */
  issuers: string[];

  /**
   * @generated from field: repeated nagipath.api.v1.DriftClusterOption clusters = 7;
   */
  clusters: DriftClusterOption[];

  /**
   * @generated from field: string summary = 8;
   */
  summary: string;
};

/**
 * Describes the message nagipath.api.v1.CertificatesListResponse.
 * Use `create(CertificatesListResponseSchema)` to create a new message.
 */
export const CertificatesListResponseSchema: GenMessage<CertificatesListResponse> = /*@__PURE__*/
  messageDesc(file_nagipath_api_v1_certificates, 1);

/**
 * @generated from message nagipath.api.v1.Certificate
 */
export type Certificate = Message<"nagipath.api.v1.Certificate"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string fingerprint = 2;
   */
  fingerprint: string;

  /**
   * @generated from field: string subject_cn = 3;
   */
  subjectCn: string;

  /**
   * @generated from field: string subject_dn = 4;
   */
  subjectDn: string;

  /**
   * @generated from field: repeated string sans = 5;
   */
  sans: string[];

  /**
   * @generated from field: string issuer_dn = 6;
   */
  issuerDn: string;

  /**
   * @generated from field: string serial = 7;
   */
  serial: string;

  /**
   * @generated from field: string not_before = 8;
   */
  notBefore: string;

  /**
   * @generated from field: string not_after = 9;
   */
  notAfter: string;

  /**
   * @generated from field: string key_algorithm = 10;
   */
  keyAlgorithm: string;

  /**
   * @generated from field: int32 key_bits = 11;
   */
  keyBits: number;

  /**
   * @generated from field: string sig_algorithm = 12;
   */
  sigAlgorithm: string;

  /**
   * @generated from field: bool self_signed = 13;
   */
  selfSigned: boolean;

  /**
   * @generated from field: bool is_ca = 14;
   */
  isCa: boolean;
};

/**
 * Describes the message nagipath.api.v1.Certificate.
 * Use `create(CertificateSchema)` to create a new message.
 */
export const CertificateSchema: GenMessage<Certificate> = /*@__PURE__*/
  messageDesc(file_nagipath_api_v1_certificates, 2);

/**
 * @generated from message nagipath.api.v1.CertBinding
 */
export type CertBinding = Message<"nagipath.api.v1.CertBinding"> & {
  /**
   * @generated from field: int64 instance_id = 1;
   */
  instanceId: bigint;

  /**
   * @generated from field: string instance = 2;
   */
  instance: string;

  /**
   * @generated from field: string node = 3;
   */
  node: string;

  /**
   * @generated from field: string cluster_name = 4;
   */
  clusterName: string;

  /**
   * @generated from field: int64 snapshot_id = 5;
   */
  snapshotId: bigint;

  /**
   * @generated from field: int64 file_id = 6;
   */
  fileId: bigint;

  /**
   * @generated from field: string file_path = 7;
   */
  filePath: string;

  /**
   * @generated from field: string site_names = 8;
   */
  siteNames: string;

  /**
   * @generated from field: int32 port = 9;
   */
  port: number;

  /**
   * @generated from field: bool combined_pem = 10;
   */
  combinedPem: boolean;
};

/**
 * Describes the message nagipath.api.v1.CertBinding.
 * Use `create(CertBindingSchema)` to create a new message.
 */
export const CertBindingSchema: GenMessage<CertBinding> = /*@__PURE__*/
  messageDesc(file_nagipath_api_v1_certificates, 3);

/**
 * @generated from message nagipath.api.v1.CertFilePath
 */
export type CertFilePath = Message<"nagipath.api.v1.CertFilePath"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: int32 node_count = 2;
   */
  nodeCount: number;

  /**
   * @generated from field: string bundle_type = 3;
   */
  bundleType: string;
};

/**
 * Describes the message nagipath.api.v1.CertFilePath.
 * Use `create(CertFilePathSchema)` to create a new message.
 */
export const CertFilePathSchema: GenMessage<CertFilePath> = /*@__PURE__*/
  messageDesc(file_nagipath_api_v1_certificates, 4);

/**
 * @generated from message nagipath.api.v1.CertificateDetailResponse
 */
export type CertificateDetailResponse = Message<"nagipath.api.v1.CertificateDetailResponse"> & {
  /**
   * @generated from field: nagipath.api.v1.Certificate cert = 1;
   */
  cert?: Certificate | undefined;

  /**
   * @generated from field: repeated nagipath.api.v1.CertBinding bindings = 2;
   */
  bindings: CertBinding[];

  /**
   * @generated from field: repeated nagipath.api.v1.CertFilePath file_paths = 3;
   */
  filePaths: CertFilePath[];

  /**
   * @generated from field: string active_tab = 4;
   */
  activeTab: string;

  /**
   * @generated from field: int32 binding_count = 5;
   */
  bindingCount: number;

  /**
   * @generated from field: int32 file_count = 6;
   */
  fileCount: number;
};

/**
 * Describes the message nagipath.api.v1.CertificateDetailResponse.
 * Use `create(CertificateDetailResponseSchema)` to create a new message.
 */
export const CertificateDetailResponseSchema: GenMessage<CertificateDetailResponse> = /*@__PURE__*/
  messageDesc(file_nagipath_api_v1_certificates, 5);

