// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file nagipath/api/v1/common.proto (package nagipath.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file nagipath/api/v1/common.proto.
 */
export const file_nagipath_api_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChxuYWdpcGF0aC9hcGkvdjEvY29tbW9uLnByb3RvEg9uYWdpcGF0aC5hcGkudjEiEAoCT2sSCgoCb2sYASABKAgiBwoFRW1wdHkiJAoKSWRSZXNwb25zZRIKCgJvaxgBIAEoCBIKCgJpZBgCIAEoA0IxWi9naXRodWIuY29tL25hZ2lmbG93L25hZ2lwYXRoL2ludGVybmFsL2FwaS9wYjtwYmIGcHJvdG8z");

/**
 * Ok is every fire-and-forget mutation's response across every service in
 * this package (a rename, a decision, a delete) — one shared message instead
 * of a near-identical one per RPC, the same reasoning ADR-0018 already gave
 * for not generating a type per bare {"ok":true} at all before RPCs existed.
 *
 * @generated from message nagipath.api.v1.Ok
 */
export type Ok = Message<"nagipath.api.v1.Ok"> & {
  /**
   * @generated from field: bool ok = 1;
   */
  ok: boolean;
};

/**
 * Describes the message nagipath.api.v1.Ok.
 * Use `create(OkSchema)` to create a new message.
 */
export const OkSchema: GenMessage<Ok> = /*@__PURE__*/
  messageDesc(file_nagipath_api_v1_common, 0);

/**
 * Empty is every RPC in this package with no request fields — a GET with no
 * query parameters. Distinct from google.protobuf.Empty only in staying a
 * local type buf doesn't need a well-known-types import for.
 *
 * @generated from message nagipath.api.v1.Empty
 */
export type Empty = Message<"nagipath.api.v1.Empty"> & {
};

/**
 * Describes the message nagipath.api.v1.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema: GenMessage<Empty> = /*@__PURE__*/
  messageDesc(file_nagipath_api_v1_common, 1);

/**
 * IdResponse is a create mutation's response across every service in this
 * package (a new credential, a new user) — {"ok":true,"id":<n>} typed.
 *
 * @generated from message nagipath.api.v1.IdResponse
 */
export type IdResponse = Message<"nagipath.api.v1.IdResponse"> & {
  /**
   * @generated from field: bool ok = 1;
   */
  ok: boolean;

  /**
   * @generated from field: int64 id = 2;
   */
  id: bigint;
};

/**
 * Describes the message nagipath.api.v1.IdResponse.
 * Use `create(IdResponseSchema)` to create a new message.
 */
export const IdResponseSchema: GenMessage<IdResponse> = /*@__PURE__*/
  messageDesc(file_nagipath_api_v1_common, 2);

