// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file nagipath/api/v1/snapshots.proto (package nagipath.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { FileRef, Instance, Snapshot } from "./nodes_pb";
import { file_nagipath_api_v1_nodes } from "./nodes_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file nagipath/api/v1/snapshots.proto.
 */
export const file_nagipath_api_v1_snapshots: GenFile = /*@__PURE__*/
  fileDesc("Ch9uYWdpcGF0aC9hcGkvdjEvc25hcHNob3RzLnByb3RvEg9uYWdpcGF0aC5hcGkudjEiuAEKC1NuYXBzaG90Um93EgoKAmlkGAEgASgDEhMKC2luc3RhbmNlX2lkGAIgASgDEhAKCGluc3RhbmNlGAMgASgJEgwKBG5vZGUYBCABKAkSDwoHY2x1c3RlchgFIAEoCRITCgtjYXB0dXJlZF9hdBgGIAEoCRIPCgd0cmlnZ2VyGAcgASgJEg8KB2NoYW5nZWQYCCABKAgSEQoJYnl0ZXNfcmF3GAkgASgDEg0KBXN0YXRlGAogASgJIsQCChVTbmFwc2hvdHNMaXN0UmVzcG9uc2USKgoEbGlzdBgBIAMoCzIcLm5hZ2lwYXRoLmFwaS52MS5TbmFwc2hvdFJvdxINCgVxdWVyeRgCIAEoCRINCgVyYW5nZRgDIAEoCRIPCgdjaGFuZ2VzGAQgASgJEg8KB3RyaWdnZXIYBSABKAkSDQoFdG90YWwYBiABKAUSEwoLdG90YWxfYnl0ZXMYByABKAMSEAoIZmlsdGVyZWQYCCABKAUSDwoHY2hhbmdlZBgJIAEoBRIQCghkZWdyYWRlZBgKIAEoBRITCgtuZXh0X2N1cnNvchgLIAEoCRIQCghoYXNfbW9yZRgMIAEoCBIMCgRmcm9tGA0gASgFEgoKAnRvGA4gASgFEg0KBWVtcHR5GA8gASgIEhYKDnJldGVudGlvbl9kYXlzGBAgASgFIvQBChRTbmFwc2hvdEZpbGVSZXNwb25zZRIrCghzbmFwc2hvdBgBIAEoCzIZLm5hZ2lwYXRoLmFwaS52MS5TbmFwc2hvdBIrCghpbnN0YW5jZRgCIAEoCzIZLm5hZ2lwYXRoLmFwaS52MS5JbnN0YW5jZRImCgRmaWxlGAMgASgLMhgubmFnaXBhdGguYXBpLnYxLkZpbGVSZWYSDAoEYm9keRgEIAEoCRISCgpieXRlX3N0YXJ0GAUgASgFEhIKCmxpbmVfc3RhcnQYBiABKAUSEAoIbGluZV9lbmQYByABKAUSEgoKaGFzX2FuY2hvchgIIAEoCEIxWi9naXRodWIuY29tL25hZ2lmbG93L25hZ2lwYXRoL2ludGVybmFsL2FwaS9wYjtwYmIGcHJvdG8z", [file_nagipath_api_v1_nodes]);

/**
 * @generated from message nagipath.api.v1.SnapshotRow
 */
export type SnapshotRow = Message<"nagipath.api.v1.SnapshotRow"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: int64 instance_id = 2;
   */
  instanceId: bigint;

  /**
   * @generated from field: string instance = 3;
   */
  instance: string;

  /**
   * @generated from field: string node = 4;
   */
  node: string;

  /**
   * @generated from field: string cluster = 5;
   */
  cluster: string;

  /**
   * @generated from field: string captured_at = 6;
   */
  capturedAt: string;

  /**
   * @generated from field: string trigger = 7;
   */
  trigger: string;

  /**
   * @generated from field: bool changed = 8;
   */
  changed: boolean;

  /**
   * @generated from field: int64 bytes_raw = 9;
   */
  bytesRaw: bigint;

  /**
   * @generated from field: string state = 10;
   */
  state: string;
};

/**
 * Describes the message nagipath.api.v1.SnapshotRow.
 * Use `create(SnapshotRowSchema)` to create a new message.
 */
export const SnapshotRowSchema: GenMessage<SnapshotRow> = /*@__PURE__*/
  messageDesc(file_nagipath_api_v1_snapshots, 0);

/**
 * @generated from message nagipath.api.v1.SnapshotsListResponse
 */
export type SnapshotsListResponse = Message<"nagipath.api.v1.SnapshotsListResponse"> & {
  /**
   * @generated from field: repeated nagipath.api.v1.SnapshotRow list = 1;
   */
  list: SnapshotRow[];

  /**
   * @generated from field: string query = 2;
   */
  query: string;

  /**
   * @generated from field: string range = 3;
   */
  range: string;

  /**
   * @generated from field: string changes = 4;
   */
  changes: string;

  /**
   * @generated from field: string trigger = 5;
   */
  trigger: string;

  /**
   * @generated from field: int32 total = 6;
   */
  total: number;

  /**
   * @generated from field: int64 total_bytes = 7;
   */
  totalBytes: bigint;

  /**
   * @generated from field: int32 filtered = 8;
   */
  filtered: number;

  /**
   * @generated from field: int32 changed = 9;
   */
  changed: number;

  /**
   * @generated from field: int32 degraded = 10;
   */
  degraded: number;

  /**
   * @generated from field: string next_cursor = 11;
   */
  nextCursor: string;

  /**
   * @generated from field: bool has_more = 12;
   */
  hasMore: boolean;

  /**
   * @generated from field: int32 from = 13;
   */
  from: number;

  /**
   * @generated from field: int32 to = 14;
   */
  to: number;

  /**
   * @generated from field: bool empty = 15;
   */
  empty: boolean;

  /**
   * @generated from field: int32 retention_days = 16;
   */
  retentionDays: number;
};

/**
 * Describes the message nagipath.api.v1.SnapshotsListResponse.
 * Use `create(SnapshotsListResponseSchema)` to create a new message.
 */
export const SnapshotsListResponseSchema: GenMessage<SnapshotsListResponse> = /*@__PURE__*/
  messageDesc(file_nagipath_api_v1_snapshots, 1);

/**
 * @generated from message nagipath.api.v1.SnapshotFileResponse
 */
export type SnapshotFileResponse = Message<"nagipath.api.v1.SnapshotFileResponse"> & {
  /**
   * @generated from field: nagipath.api.v1.Snapshot snapshot = 1;
   */
  snapshot?: Snapshot | undefined;

  /**
   * @generated from field: nagipath.api.v1.Instance instance = 2;
   */
  instance?: Instance | undefined;

  /**
   * @generated from field: nagipath.api.v1.FileRef file = 3;
   */
  file?: FileRef | undefined;

  /**
   * @generated from field: string body = 4;
   */
  body: string;

  /**
   * @generated from field: int32 byte_start = 5;
   */
  byteStart: number;

  /**
   * @generated from field: int32 line_start = 6;
   */
  lineStart: number;

  /**
   * @generated from field: int32 line_end = 7;
   */
  lineEnd: number;

  /**
   * @generated from field: bool has_anchor = 8;
   */
  hasAnchor: boolean;
};

/**
 * Describes the message nagipath.api.v1.SnapshotFileResponse.
 * Use `create(SnapshotFileResponseSchema)` to create a new message.
 */
export const SnapshotFileResponseSchema: GenMessage<SnapshotFileResponse> = /*@__PURE__*/
  messageDesc(file_nagipath_api_v1_snapshots, 2);

